/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.baquiax.ventana;

import com.baquiax.analizadorlexico.AnalizadorLexico;
import com.baquiax.manejoArchivo.ManejoArchivo;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.BadLocationException;

/**
 *
 * @author luis
 */
public class Analizador extends javax.swing.JFrame {

    private AnalizadorLexico analizadorLexico;
    private ManejoArchivo manejoArchivo;
    private String path;

    /**
     * Creates new form Analizador
     */
    public Analizador() {
        initComponents();
        ponerFilaColumanCursor();
        this.menuReporteErrores.setEnabled(false);
        this.menuReporteTokens.setEnabled(false);
        this.manejoArchivo = new ManejoArchivo();
        this.path = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelContenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        txtAnalizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        labelFilaColumna = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContadorFilas = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuAbrirArchivo = new javax.swing.JMenuItem();
        menuGuardarComo = new javax.swing.JMenuItem();
        menuGuardarCambios = new javax.swing.JMenu();
        menuReportes = new javax.swing.JMenu();
        menuReporteErrores = new javax.swing.JMenuItem();
        menuReporteTokens = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtAnalizar.setText("Analizar texto");
        txtAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304)
                .addComponent(txtAnalizar)
                .addContainerGap(697, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnalizar)))
        );

        txtTexto.setColumns(20);
        txtTexto.setRows(5);
        txtTexto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtTextoMouseMoved(evt);
            }
        });
        txtTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTextoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtTexto);

        labelFilaColumna.setText("Fila-columna");

        txtContadorFilas.setEditable(false);
        txtContadorFilas.setBackground(new java.awt.Color(238, 238, 238));
        txtContadorFilas.setColumns(20);
        txtContadorFilas.setRows(5);
        txtContadorFilas.setAutoscrolls(false);
        jScrollPane2.setViewportView(txtContadorFilas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1369, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelFilaColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(579, 579, 579))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFilaColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpanelContenedorLayout = new javax.swing.GroupLayout(jpanelContenedor);
        jpanelContenedor.setLayout(jpanelContenedorLayout);
        jpanelContenedorLayout.setHorizontalGroup(
            jpanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanelContenedorLayout.setVerticalGroup(
            jpanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelContenedorLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuFile.setText("File");

        menuAbrirArchivo.setText("Abrir archivo");
        menuAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirArchivoActionPerformed(evt);
            }
        });
        menuFile.add(menuAbrirArchivo);

        menuGuardarComo.setText("Guardar como");
        menuGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarComoActionPerformed(evt);
            }
        });
        menuFile.add(menuGuardarComo);

        jMenuBar1.add(menuFile);

        menuGuardarCambios.setText("Guardar cambios");
        menuGuardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGuardarCambiosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuGuardarCambios);

        menuReportes.setText("Reportes");

        menuReporteErrores.setText("Reporte de errores");
        menuReporteErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporteErroresActionPerformed(evt);
            }
        });
        menuReportes.add(menuReporteErrores);

        menuReporteTokens.setText("Reporte tokens");
        menuReporteTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporteTokensActionPerformed(evt);
            }
        });
        menuReportes.add(menuReporteTokens);

        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        PalabrasFiltradas p = new PalabrasFiltradas(this.txtBuscar.getText(), this.txtTexto);
        p.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void menuReporteErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteErroresActionPerformed
        // TODO add your handling code here:
        this.analizadorLexico.analizarTexto(this.txtTexto.getText());
        ReporteErrores re = new ReporteErrores(this.analizadorLexico, this);
        re.setVisible(true);
        super.setVisible(false);
    }//GEN-LAST:event_menuReporteErroresActionPerformed

    private void menuReporteTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteTokensActionPerformed
        // TODO add your handling code here:

//        this.analizadorLexico.analizarTexto(this.txtTexto.getText());
//        ReporteTokens to = new ReporteTokens(this.analizadorLexico, this);
//        to.setVisible(true);
//        super.setVisible(false);
        if (analizadorLexico.getListCadenaErrors().isEmpty()) {
            this.analizadorLexico.analizarTexto(this.txtTexto.getText());
            ReporteTokens to = new ReporteTokens(this.analizadorLexico, this);
            to.setVisible(true);
            super.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Debes corregir los errores y luego analizar nuevamente el texto.");
        }

    }//GEN-LAST:event_menuReporteTokensActionPerformed

    private void txtAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnalizarActionPerformed
        // TODO add your handling code here:
        this.analizadorLexico = new AnalizadorLexico();
        this.analizadorLexico.analizarTexto(this.txtTexto.getText());
        this.menuReporteErrores.setEnabled(true);
        this.menuReporteTokens.setEnabled(true);
    }//GEN-LAST:event_txtAnalizarActionPerformed

    private void txtTextoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTextoMouseMoved
        // TODO add your handling code here:
        contadorFilas();
    }//GEN-LAST:event_txtTextoMouseMoved

    private void txtTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextoKeyTyped
        // TODO add your handling code here:
        contadorFilas();
    }//GEN-LAST:event_txtTextoKeyTyped

    private void menuAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirArchivoActionPerformed
        try {
            // TODO add your handling code here:
            this.path = this.manejoArchivo.pathChoserOpen();
            this.txtTexto.setText(manejoArchivo.leerArchivo(path));
        } catch (IOException ex) {
            System.out.println("No se pudo abrir el archivo" + ex.getMessage());
        }
    }//GEN-LAST:event_menuAbrirArchivoActionPerformed

    private void menuGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarComoActionPerformed
        // TODO add your handling code here:
        String ruta = this.manejoArchivo.pathChoserSave();
        this.manejoArchivo.escribirArchivodeTexto(ruta, txtTexto.getText());
    }//GEN-LAST:event_menuGuardarComoActionPerformed

    private void menuGuardarCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGuardarCambiosMouseClicked
        // TODO add your handling code here:
        guardarComo();
    }//GEN-LAST:event_menuGuardarCambiosMouseClicked

    private void guardarComo() {
        if ("".equals(path)) {
            String ruta = this.manejoArchivo.pathChoserSave();
            this.manejoArchivo.escribirArchivodeTexto(ruta, txtTexto.getText());
        } else {
            this.manejoArchivo.escribirArchivodeTexto(path, txtTexto.getText());
        }

    }

    /**
     * Cuenta las filas del texto
     */
    private void contadorFilas() {
        int numeroFilas = 0;
        for (int i = 0; i < this.txtTexto.getText().length(); i++) {
            if (this.txtTexto.getText().charAt(i) == '\n') {
                numeroFilas++;
            }
        }
        String ayuda = "";
        for (int i = 0; i < numeroFilas + 1; i++) {
            ayuda += (i + 1) + "\n";
        }
        this.txtContadorFilas.setText(ayuda);
    }

    /**
     * Pone la fila y columna en el que se encuentra el cursor
     */
    private void ponerFilaColumanCursor() {
        txtTexto.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent e) {
                //Devuelve la ubicación actual del símbolo de intercalación. 
                int pos = e.getDot();
                try {
                    int fila = txtTexto.getLineOfOffset(pos) + 1;
                    int col = pos - txtTexto.getLineStartOffset(fila - 1) + 1;
                    labelFilaColumna.setText("Fila: " + fila + " Columna: " + col);
                } catch (BadLocationException exc) {
                    System.out.println(exc);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpanelContenedor;
    private javax.swing.JLabel labelFilaColumna;
    private javax.swing.JMenuItem menuAbrirArchivo;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuGuardarCambios;
    private javax.swing.JMenuItem menuGuardarComo;
    private javax.swing.JMenuItem menuReporteErrores;
    private javax.swing.JMenuItem menuReporteTokens;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JButton txtAnalizar;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtContadorFilas;
    private javax.swing.JTextArea txtTexto;
    // End of variables declaration//GEN-END:variables
}
